/* ============================================================================
 *  IQ TEST v5 — Science-Grade Cognitive Assessment (NeuroZen)
 *  ---------------------------------------------------------------------------
 *  Entry (unchanged host contract): playIQTest(body, setScore, end, wrap, startClock)
 *  Host globals used (do NOT redefine): $, S, setS, playSound, toast, confetti,
 *    _si, _cti, _st, todayKey, haptic
 *  localStorage keys: nz_iq_best, nz_iq_games, nz_iq_profile, nz_iq_onboard,
 *                     nz_iq_cbsafe
 *  CSS prefix: .iq-  (styles live in css/style.css, iqv5 block at bottom)
 *
 *  Rebuild philosophy:
 *   - Feels like a real cognitive assessment, not an MCQ quiz.
 *   - 25 curated questions, deterministic order (difficulty ramp Easy→Hard).
 *   - ≥60% non-verbal (visual matrices, spatial rotation, cube nets, paper
 *     folds, abstract sequences). Every visual is generated by an inline SVG
 *     toolkit from a small data payload — no hand-written SVG blobs.
 *   - Scoring: per-Q base × difficulty × speed bonus × streak → IQ-style score
 *     (mean 100, SD 15). Percentile from a bell-curve lookup.
 *   - Premium results screen: animated big score, radar chart over 5 skills,
 *     per-skill bars + verdicts, personalised tips, share card.
 *   - Preserves every host integration hook: it still calls setScore() during
 *     the test, and end({title, emoji, sub, value, points, starThresh,
 *     statsHtml}) at the finish — so app.js's XP / brain-score / mastery /
 *     achievement / daily-challenge pipeline keeps working unchanged.
 * ============================================================================ */

/* ---------- Legacy exports kept for compatibility with app.js -------------- */
/* Even though the new test doesn't use IQ_POOL / IQ_TIMER, other places in the
   host (achievements etc.) reference the module-level names, so we keep the
   symbols exported to `window` with sensible values. */
const IQ_POOL = [];               /* deliberately empty: new engine is curated */
const IQ_CATS = {
  pattern : { label:'🧩 Pattern', color:'#7C3AED', icon:'🧩' },
  spatial : { label:'📐 Spatial', color:'#F97316', icon:'📐' },
  logic   : { label:'🧠 Logic',   color:'#4F8EF7', icon:'🧠' },
  memory  : { label:'🧩 Memory',  color:'#06B6D4', icon:'🧩' },
  speed   : { label:'⚡ Speed',   color:'#EAB308', icon:'⚡'  }
};
const IQ_DIFF_W = { 1:1, 2:2, 3:3, easy:1, medium:2, hard:3 };
const IQ_TIMER  = { 1:20000, 2:30000, 3:45000, easy:20000, medium:30000, hard:45000 };
const IQ_N      = 25;

function iqClassify(iq){
  if(iq>=140) return { label:'🌟 Genius',          pct:99, color:'#F97316' };
  if(iq>=130) return { label:'⚡ Very Superior',    pct:98, color:'#7C3AED' };
  if(iq>=120) return { label:'🏆 Superior',        pct:91, color:'#4F8EF7' };
  if(iq>=110) return { label:'🧠 Above Average',   pct:75, color:'#34D399' };
  if(iq>=90)  return { label:'💪 Average',         pct:50, color:'#22C55E' };
  if(iq>=80)  return { label:'📈 Below Average',   pct:25, color:'#EAB308' };
  return       { label:'🌱 Keep Practicing',       pct:10, color:'#94A3B8' };
}

/* Small helpers used both by the SVG toolkit and by the renderer. */
function IQ_rand(n){ return Math.floor(Math.random()*n); }
function IQ_pick(a){ return a[IQ_rand(a.length)]; }
function IQ_shuffle(a){
  const x=a.slice();
  for(let i=x.length-1;i>0;i--){ const j=IQ_rand(i+1); [x[i],x[j]]=[x[j],x[i]]; }
  return x;
}
function IQ_clamp(v,lo,hi){ return Math.max(lo, Math.min(hi, v)); }
function IQ_bellCurvePctile(iq){
  /* Approx normal(100,15) CDF via erf approximation → percentile 1..99. */
  const z=(iq-100)/15;
  const t=1/(1+0.2316419*Math.abs(z));
  const d=0.3989423*Math.exp(-z*z/2);
  const p=d*t*(0.3193815+t*(-0.3565638+t*(1.781478+t*(-1.821256+t*1.330274))));
  const cdf=z>0 ? 1-p : p;
  return IQ_clamp(Math.round(cdf*100),1,99);
}

/* ============================================================================
 *  SECTION 1 — SVG TOOLKIT
 *  ---------------------------------------------------------------------------
 *  Every visual in the test is generated from a small data payload by these
 *  helpers. This keeps the question data compact (~1-3 lines each) and lets us
 *  add more questions later with zero SVG hand-editing.
 * ============================================================================ */

/* Color palette read from CSS variables at first use, with sensible fallbacks
 * so nothing looks broken if a variable is missing. We also honor a colorblind-
 * safe toggle stored in localStorage (nz_iq_cbsafe). */
function IQ_palette(){
  try{
    const cs=getComputedStyle(document.documentElement);
    const cb=!!S('nz_iq_cbsafe');
    return {
      ink   : (cs.getPropertyValue('--text')  ||'#0F172A').trim(),
      muted : (cs.getPropertyValue('--text2') ||'#64748B').trim(),
      line  : (cs.getPropertyValue('--border')||'#E5E7EB').trim(),
      surf  : (cs.getPropertyValue('--card')  ||'#FFFFFF').trim(),
      prim  : (cs.getPropertyValue('--primary')||'#7C3AED').trim(),
      accent: '#4F8EF7',
      good  : cb ? '#2563EB' : '#22C55E',
      bad   : cb ? '#EA580C' : '#EF4444',
      warn  : '#F59E0B',
      cb    : cb
    };
  }catch(e){
    return { ink:'#0F172A', muted:'#64748B', line:'#E5E7EB', surf:'#FFFFFF',
             prim:'#7C3AED', accent:'#4F8EF7', good:'#22C55E', bad:'#EF4444',
             warn:'#F59E0B', cb:false };
  }
}

/* Build one primitive shape centered at (cx,cy) inside a bbox of size `sz`.
 * `spec` is a small object: { kind, fill?, stroke?, rot?, count?, size? }.
 * Kinds: circle, square, triangle, diamond, star, cross, arrow, dot, ring,
 *        hex, halfcircle, tri-down. */
function IQ_shape(spec, cx, cy, sz){
  const p=IQ_palette();
  const stroke = spec.stroke || p.ink;
  const fill   = spec.fill   || 'none';
  const sw     = spec.sw != null ? spec.sw : 2;
  const rot    = spec.rot || 0;
  const s      = (spec.size!=null ? spec.size : 1) * sz * 0.42;
  const g = `<g transform="translate(${cx} ${cy}) rotate(${rot})">`;
  const attrs = `fill="${fill}" stroke="${stroke}" stroke-width="${sw}" stroke-linejoin="round" stroke-linecap="round"`;
  let body='';
  switch(spec.kind){
    case 'circle':      body=`<circle cx="0" cy="0" r="${s}" ${attrs}/>`; break;
    case 'ring':        body=`<circle cx="0" cy="0" r="${s}" fill="none" stroke="${stroke}" stroke-width="${sw}"/>`; break;
    case 'dot':         body=`<circle cx="0" cy="0" r="${s*0.35}" fill="${stroke}" stroke="none"/>`; break;
    case 'square':      body=`<rect x="${-s}" y="${-s}" width="${s*2}" height="${s*2}" ${attrs}/>`; break;
    case 'diamond':     body=`<polygon points="0,${-s} ${s},0 0,${s} ${-s},0" ${attrs}/>`; break;
    case 'triangle':    body=`<polygon points="0,${-s} ${s*0.92},${s*0.72} ${-s*0.92},${s*0.72}" ${attrs}/>`; break;
    case 'tri-down':    body=`<polygon points="0,${s} ${s*0.92},${-s*0.72} ${-s*0.92},${-s*0.72}" ${attrs}/>`; break;
    case 'hex': {
      const pts=[];for(let i=0;i<6;i++){const a=(Math.PI/3)*i-Math.PI/2;pts.push(`${(Math.cos(a)*s).toFixed(2)},${(Math.sin(a)*s).toFixed(2)}`);}
      body=`<polygon points="${pts.join(' ')}" ${attrs}/>`; break;
    }
    case 'star': {
      const pts=[];for(let i=0;i<10;i++){const a=(Math.PI/5)*i-Math.PI/2;const r=(i%2)?s*0.45:s;pts.push(`${(Math.cos(a)*r).toFixed(2)},${(Math.sin(a)*r).toFixed(2)}`);}
      body=`<polygon points="${pts.join(' ')}" ${attrs}/>`; break;
    }
    case 'cross':       body=`<path d="M ${-s} 0 L ${s} 0 M 0 ${-s} L 0 ${s}" fill="none" stroke="${stroke}" stroke-width="${sw*1.4}" stroke-linecap="round"/>`; break;
    case 'arrow':       body=`<path d="M ${-s} 0 L ${s*0.7} 0 M ${s*0.7} 0 L ${s*0.2} ${-s*0.5} M ${s*0.7} 0 L ${s*0.2} ${s*0.5}" fill="none" stroke="${stroke}" stroke-width="${sw*1.4}" stroke-linecap="round" stroke-linejoin="round"/>`; break;
    case 'halfcircle':  body=`<path d="M ${-s} 0 A ${s} ${s} 0 0 1 ${s} 0 Z" ${attrs}/>`; break;
    case 'plus':        body=`<path d="M ${-s*0.35} ${-s} h ${s*0.7} v ${s*0.65} h ${s*0.65} v ${s*0.7} h ${-s*0.65} v ${s*0.65} h ${-s*0.7} v ${-s*0.65} h ${-s*0.65} v ${-s*0.7} h ${s*0.65} Z" ${attrs}/>`; break;
    case 'l-shape':     body=`<path d="M ${-s} ${-s} h ${s*2} v ${s*0.75} h ${-s*1.25} v ${s*1.25} h ${-s*0.75} Z" ${attrs}/>`; break;
    default:            body='';
  }
  return g + body + '</g>';
}

/* Draw N shapes evenly in a cell — used for count-progression matrices. */
function IQ_shapesInCell(spec, count, cx, cy, sz){
  if(count<=0) return '';
  const R = sz*0.28;
  let out='';
  if(count===1){
    out += IQ_shape({...spec, size:0.9}, cx, cy, sz);
  }else{
    for(let i=0;i<count;i++){
      const a=(Math.PI*2/count)*i - Math.PI/2;
      const x=cx+Math.cos(a)*R;
      const y=cy+Math.sin(a)*R;
      out += IQ_shape({...spec, size:0.55}, x, y, sz);
    }
  }
  return out;
}

/* One matrix cell painter. `cellSpec` is one of:
 *   { blank:true }                                   → the "?" cell
 *   { kind, rot?, count?, fill?, stroke?, size? }    → single shape
 *   { multi:[cellSpec, ...] }                        → overlay multiple shapes
 *   { count, kind, fill?, stroke? }                  → draw `count` copies
 */
function IQ_matrixCell(cellSpec, cx, cy, sz, opts){
  const p=IQ_palette();
  const isBlank=!!(cellSpec && cellSpec.blank);
  const border=`<rect x="${cx-sz/2}" y="${cy-sz/2}" width="${sz}" height="${sz}" rx="8" ry="8" fill="${(opts&&opts.bg)||'transparent'}" stroke="${(opts&&opts.borderColor)||p.line}" stroke-width="1.5"/>`;
  let content='';
  if(isBlank){
    content = `<text x="${cx}" y="${cy+sz*0.14}" text-anchor="middle" font-size="${sz*0.42}" font-weight="800" fill="${p.muted}" font-family="system-ui,-apple-system,sans-serif">?</text>`;
  }else if(cellSpec && cellSpec.multi){
    for(const s of cellSpec.multi) content += IQ_shape(s, cx, cy, sz);
  }else if(cellSpec && cellSpec.count!=null){
    content = IQ_shapesInCell(cellSpec, cellSpec.count, cx, cy, sz);
  }else if(cellSpec){
    content = IQ_shape(cellSpec, cx, cy, sz);
  }
  return border + content;
}

/* Draw an R×C matrix from a flat array of cellSpecs (row-major). */
function IQ_drawMatrix(rows, cols, cells, opts){
  const w = 240, h = 240;
  const pad = 10;
  const cw = (w - pad*2)/cols, ch = (h - pad*2)/rows;
  const sz = Math.min(cw, ch) - 8;
  let svg = `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" class="iq-svg iq-svg-matrix">`;
  for(let r=0;r<rows;r++){
    for(let c=0;c<cols;c++){
      const cx = pad + cw*c + cw/2;
      const cy = pad + ch*r + ch/2;
      const spec = cells[r*cols + c];
      svg += IQ_matrixCell(spec, cx, cy, sz, opts||{});
    }
  }
  svg += '</svg>';
  return svg;
}

/* Small "option tile" — a bordered box drawing exactly one cellSpec. Used for
 * A/B/C/D visual choices in matrix, rotation, sequence questions. */
function IQ_optionTile(cellSpec){
  const p=IQ_palette();
  const w=90,h=90,cx=w/2,cy=h/2,sz=w-16;
  let svg=`<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" class="iq-svg iq-svg-opt">`;
  svg += IQ_matrixCell(cellSpec, cx, cy, sz, {borderColor:'transparent'});
  svg += '</svg>';
  return svg;
}

/* Simple horizontal sequence: N frames left→right with an arrow, last is "?". */
function IQ_drawSequence(cells){
  const p=IQ_palette();
  const n=cells.length;
  const cw=70, gap=8;
  const w = n*cw + (n-1)*gap + 20;
  const h = 90;
  let svg=`<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" class="iq-svg iq-svg-seq">`;
  for(let i=0;i<n;i++){
    const cx = 10 + i*(cw+gap) + cw/2;
    const cy = h/2;
    svg += IQ_matrixCell(cells[i], cx, cy, cw-8, {});
    if(i<n-1){
      const ax = 10 + (i+1)*cw + i*gap - 2;
      svg += `<path d="M ${ax} ${cy} l ${gap+4} 0" stroke="${p.muted}" stroke-width="1.5" stroke-linecap="round"/>`;
    }
  }
  svg += '</svg>';
  return svg;
}

/* Cube-net drawing: a cross-shape unfolded cube with 6 labeled faces. */
function IQ_drawCubeNet(faceLabels, faceColors){
  const p=IQ_palette();
  const s=42;
  const w=s*4+20, h=s*3+20;
  const ox=10, oy=10;
  /* Positions in a cross: [col,row] for faces top, left, front, right, back, bottom */
  const pos=[ [1,0], [0,1], [1,1], [2,1], [3,1], [1,2] ];
  let svg=`<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" class="iq-svg iq-svg-cube">`;
  for(let i=0;i<6;i++){
    const [c,r]=pos[i];
    const x=ox+c*s, y=oy+r*s;
    const fill=(faceColors&&faceColors[i])||p.surf;
    svg += `<rect x="${x}" y="${y}" width="${s}" height="${s}" rx="4" ry="4" fill="${fill}" stroke="${p.ink}" stroke-width="1.5"/>`;
    if(faceLabels&&faceLabels[i]){
      svg += `<text x="${x+s/2}" y="${y+s/2+5}" text-anchor="middle" font-size="16" font-weight="800" fill="${p.ink}" font-family="system-ui,sans-serif">${faceLabels[i]}</text>`;
    }
  }
  svg += '</svg>';
  return svg;
}

/* Draw a folded-cube option: an isometric cube showing 3 visible faces with
 * labels. Used as the 4 options for cube-net questions. */
function IQ_drawFoldedCube(visibleFaces /* {top,left,right}*/){
  const p=IQ_palette();
  const w=110,h=110;
  const cx=w/2, cy=h/2+6;
  const s=32;
  /* Face polygon coordinates */
  const top   = `${cx},${cy-s} ${cx+s*0.86},${cy-s*0.5} ${cx},${cy} ${cx-s*0.86},${cy-s*0.5}`;
  const left  = `${cx-s*0.86},${cy-s*0.5} ${cx},${cy} ${cx},${cy+s} ${cx-s*0.86},${cy+s*0.5}`;
  const right = `${cx+s*0.86},${cy-s*0.5} ${cx},${cy} ${cx},${cy+s} ${cx+s*0.86},${cy+s*0.5}`;
  let svg=`<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" class="iq-svg iq-svg-cube3d">`;
  svg += `<polygon points="${top}"   fill="#F1F5F9" stroke="${p.ink}" stroke-width="1.5"/>`;
  svg += `<polygon points="${left}"  fill="#E2E8F0" stroke="${p.ink}" stroke-width="1.5"/>`;
  svg += `<polygon points="${right}" fill="#CBD5E1" stroke="${p.ink}" stroke-width="1.5"/>`;
  const label=(txt,x,y)=>`<text x="${x}" y="${y}" text-anchor="middle" font-size="14" font-weight="800" fill="${p.ink}" font-family="system-ui,sans-serif">${txt}</text>`;
  if(visibleFaces.top)   svg += label(visibleFaces.top,   cx,          cy-s*0.5+5);
  if(visibleFaces.left)  svg += label(visibleFaces.left,  cx-s*0.42,   cy+s*0.35);
  if(visibleFaces.right) svg += label(visibleFaces.right, cx+s*0.42,   cy+s*0.35);
  svg += '</svg>';
  return svg;
}

/* Paper-fold visualisation: a small strip showing fold steps then a punched
 * paper. Renders the unfolded result option as a grid of holes. */
function IQ_drawFoldSteps(folds, punchAt /* [ [x,y], ... ] */){
  const p=IQ_palette();
  const w=180, h=90;
  const sz=56;
  let svg=`<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" class="iq-svg iq-svg-fold">`;
  /* Left: full square */
  svg += `<rect x="10" y="17" width="${sz}" height="${sz}" fill="${p.surf}" stroke="${p.ink}" stroke-width="1.5"/>`;
  /* Middle: after folds — thick outline showing halved paper */
  svg += `<rect x="80" y="17" width="${sz*0.5}" height="${sz}" fill="${p.surf}" stroke="${p.ink}" stroke-width="1.5"/>`;
  svg += `<path d="M ${80+sz*0.5} 17 L ${80+sz*0.5} ${17+sz}" stroke="${p.muted}" stroke-width="1" stroke-dasharray="3 3"/>`;
  /* Right: punched */
  svg += `<rect x="130" y="17" width="${sz*0.5}" height="${sz}" fill="${p.surf}" stroke="${p.ink}" stroke-width="1.5"/>`;
  for(const pt of punchAt){
    const px = 130 + pt[0]*sz*0.5;
    const py = 17  + pt[1]*sz;
    svg += `<circle cx="${px}" cy="${py}" r="3.5" fill="${p.bad}"/>`;
  }
  svg += `<text x="38" y="82" text-anchor="middle" font-size="9" fill="${p.muted}">fold</text>`;
  svg += `<text x="105" y="82" text-anchor="middle" font-size="9" fill="${p.muted}">punch</text>`;
  svg += `<text x="155" y="82" text-anchor="middle" font-size="9" fill="${p.muted}">unfold=?</text>`;
  svg += '</svg>';
  return svg;
}

/* Unfolded paper option: 2×2 grid, dots at requested cells. */
function IQ_drawUnfolded(holes /* Set of "r,c" */){
  const p=IQ_palette();
  const w=90,h=90;
  const gs=32, ox=(w-gs*2)/2, oy=(h-gs*2)/2;
  let svg=`<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" class="iq-svg iq-svg-unfold">`;
  svg += `<rect x="${ox}" y="${oy}" width="${gs*2}" height="${gs*2}" fill="${p.surf}" stroke="${p.ink}" stroke-width="1.5"/>`;
  svg += `<line x1="${ox+gs}" y1="${oy}" x2="${ox+gs}" y2="${oy+gs*2}" stroke="${p.muted}" stroke-width="1" stroke-dasharray="3 3"/>`;
  svg += `<line x1="${ox}" y1="${oy+gs}" x2="${ox+gs*2}" y2="${oy+gs}" stroke="${p.muted}" stroke-width="1" stroke-dasharray="3 3"/>`;
  for(let r=0;r<2;r++)for(let c=0;c<2;c++){
    if(holes.has(r+','+c)){
      svg += `<circle cx="${ox+gs*c+gs/2}" cy="${oy+gs*r+gs/2}" r="5" fill="${p.bad}"/>`;
    }
  }
  svg += '</svg>';
  return svg;
}

/* Circular countdown timer — the "hero" clock. Redraws via updates to
 * strokeDashoffset (cheap, GPU-accelerated). Colour ramps green→amber→red. */
function IQ_makeTimerRing(size){
  const p=IQ_palette();
  const r=size/2 - 6;
  const c=2*Math.PI*r;
  const el = document.createElement('div');
  el.className='iq-ring-wrap';
  el.style.width=size+'px';el.style.height=size+'px';
  el.innerHTML =
    `<svg viewBox="0 0 ${size} ${size}" class="iq-ring" width="${size}" height="${size}">`+
      `<circle cx="${size/2}" cy="${size/2}" r="${r}" fill="none" stroke="${p.line}" stroke-width="5"/>`+
      `<circle cx="${size/2}" cy="${size/2}" r="${r}" fill="none" stroke="${p.good}" stroke-width="5" stroke-linecap="round" `+
        `stroke-dasharray="${c}" stroke-dashoffset="0" transform="rotate(-90 ${size/2} ${size/2})" class="iq-ring-arc"/>`+
    `</svg>`+
    `<div class="iq-ring-num">0</div>`;
  const arc = el.querySelector('.iq-ring-arc');
  const num = el.querySelector('.iq-ring-num');
  return {
    el, arc, num, circumference:c,
    set(fracLeft, secsLeft){
      const off = c * (1 - fracLeft);
      arc.setAttribute('stroke-dashoffset', off);
      let color = p.good;
      if(fracLeft < 0.25) color = p.bad;
      else if(fracLeft < 0.5) color = p.warn;
      arc.setAttribute('stroke', color);
      num.textContent = Math.max(0, Math.ceil(secsLeft));
      el.classList.toggle('iq-ring-critical', secsLeft <= 3);
    }
  };
}

/* Radar chart SVG for the 5 skill scores (0..1). */
function IQ_drawRadar(scores /* {pattern,spatial,logic,memory,speed} in 0..1 */){
  const p=IQ_palette();
  const labels=['Pattern','Spatial','Logic','Memory','Speed'];
  const keys=['pattern','spatial','logic','memory','speed'];
  const w=240,h=220,cx=w/2,cy=h/2+4,R=76;
  const pts=(vals)=>vals.map((v,i)=>{
    const a=(Math.PI*2/5)*i - Math.PI/2;
    const r=R*IQ_clamp(v,0,1);
    return [cx+Math.cos(a)*r, cy+Math.sin(a)*r];
  });
  let svg=`<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" class="iq-svg iq-svg-radar">`;
  /* rings */
  for(let k=1;k<=4;k++){
    const rr=R*k/4;
    const ringPts=[];for(let i=0;i<5;i++){const a=(Math.PI*2/5)*i - Math.PI/2;ringPts.push(`${cx+Math.cos(a)*rr},${cy+Math.sin(a)*rr}`);}
    svg += `<polygon points="${ringPts.join(' ')}" fill="none" stroke="${p.line}" stroke-width="1"/>`;
  }
  /* axes */
  for(let i=0;i<5;i++){
    const a=(Math.PI*2/5)*i - Math.PI/2;
    svg += `<line x1="${cx}" y1="${cy}" x2="${cx+Math.cos(a)*R}" y2="${cy+Math.sin(a)*R}" stroke="${p.line}" stroke-width="1"/>`;
  }
  /* filled polygon */
  const vals=keys.map(k=>scores[k]||0);
  const poly=pts(vals).map(pp=>pp.join(',')).join(' ');
  svg += `<polygon points="${poly}" fill="${p.prim}33" stroke="${p.prim}" stroke-width="2" stroke-linejoin="round"/>`;
  /* dots */
  for(const [x,y] of pts(vals)) svg += `<circle cx="${x}" cy="${y}" r="3" fill="${p.prim}"/>`;
  /* labels */
  for(let i=0;i<5;i++){
    const a=(Math.PI*2/5)*i - Math.PI/2;
    const lx=cx+Math.cos(a)*(R+18);
    const ly=cy+Math.sin(a)*(R+18)+4;
    svg += `<text x="${lx}" y="${ly}" text-anchor="middle" font-size="11" font-weight="700" fill="${p.ink}" font-family="system-ui,sans-serif">${labels[i]}</text>`;
  }
  svg += '</svg>';
  return svg;
}

/* ============================================================================
 *  SECTION 2 — QUESTION BANK (exactly 25 curated items)
 *  ---------------------------------------------------------------------------
 *  Order is INTENTIONAL: warmup easy → medium → hard, with 2 boss questions
 *  near the end. Every visual is produced from a small `payload` via the SVG
 *  toolkit above. No hand-authored SVG blobs.
 * ============================================================================ */

/* --- helpers to author matrix questions concisely ------------------------- */
function IQ_shp(kind, extra){ return Object.assign({kind}, extra||{}); }
function IQ_correctIdxFrom(id, opts){ return opts.findIndex(o=>o.id===id); }

const IQ_QUESTIONS = [

  /* === Q1 — EASY · MATRIX (count progression) ================================
     Row1: 1,2,3 · Row2: 2,3,4 · Row3: 3,4,? → 5 dots. */
  {
    id:'q1', category:'pattern', difficulty:1,
    modality:'visual', render:'matrix',
    prompt:'Find the tile that completes the pattern.',
    payload:{
      rows:3, cols:3,
      cells:[
        {kind:'circle', count:1}, {kind:'circle', count:2}, {kind:'circle', count:3},
        {kind:'circle', count:2}, {kind:'circle', count:3}, {kind:'circle', count:4},
        {kind:'circle', count:3}, {kind:'circle', count:4}, {blank:true}
      ]
    },
    options:[
      {id:'a', spec:{kind:'circle', count:4}},
      {id:'b', spec:{kind:'circle', count:5}},
      {id:'c', spec:{kind:'circle', count:3}},
      {id:'d', spec:{kind:'circle', count:6}}
    ],
    correct:'b',
    explanation:'Har row aur column mein circles ek-ek badhte hain. Bottom-right cell = 5.',
    skills:['pattern'], timeLimit:20
  },

  /* === Q2 — EASY · SEQUENCE (rotation +90°) =================================
     Arrow rotates 90° clockwise each step. */
  {
    id:'q2', category:'pattern', difficulty:1,
    modality:'visual', render:'sequence',
    prompt:'Which shape comes next in the series?',
    payload:{
      cells:[
        {kind:'arrow', rot:0},   {kind:'arrow', rot:90},
        {kind:'arrow', rot:180}, {kind:'arrow', rot:270}, {blank:true}
      ]
    },
    options:[
      {id:'a', spec:{kind:'arrow', rot:0}},
      {id:'b', spec:{kind:'arrow', rot:45}},
      {id:'c', spec:{kind:'arrow', rot:180}},
      {id:'d', spec:{kind:'arrow', rot:90}}
    ],
    correct:'a',
    explanation:'Har step +90° clockwise. 270°+90° = 360° = 0° → wapas original direction.',
    skills:['pattern','spatial'], timeLimit:20
  },

  /* === Q3 — EASY · SPATIAL (mirror detection) ================================
     Which option is a mirror image of the target (not a rotation)? */
  {
    id:'q3', category:'spatial', difficulty:1,
    modality:'visual', render:'mirror',
    prompt:'Which option is a MIRROR image of the shape below? (not just rotated)',
    payload:{
      target:{kind:'l-shape', rot:0}
    },
    options:[
      {id:'a', spec:{kind:'l-shape', rot:90}},
      {id:'b', spec:{kind:'l-shape', rot:180}},
      {id:'c', spec:{kind:'l-shape', rot:0, mirror:true}},
      {id:'d', spec:{kind:'l-shape', rot:270}}
    ],
    correct:'c',
    explanation:'Mirror flip left↔right (horizontal flip). Rotation same shape rakhta hai; mirror ek "flipped" version banata hai.',
    skills:['spatial'], timeLimit:22
  },

  /* === Q4 — EASY · SEQUENCE (shape morph) ====================================
     Triangle → Square → Pentagon-ish (hex) → Circle → ? (dot). Actually use
     a simple size shrink. */
  {
    id:'q4', category:'pattern', difficulty:1,
    modality:'visual', render:'sequence',
    prompt:'What comes next? Size decreases each step.',
    payload:{
      cells:[
        {kind:'square', size:1.0}, {kind:'square', size:0.8},
        {kind:'square', size:0.6}, {kind:'square', size:0.4}, {blank:true}
      ]
    },
    options:[
      {id:'a', spec:{kind:'square', size:0.4}},
      {id:'b', spec:{kind:'square', size:0.2}},
      {id:'c', spec:{kind:'circle', size:0.2}},
      {id:'d', spec:{kind:'square', size:0.6}}
    ],
    correct:'b',
    explanation:'Har step size ~0.2 kam ho rahi hai. 0.4 ke baad 0.2.',
    skills:['pattern'], timeLimit:20
  },

  /* === Q5 — EASY · LOGIC (transitive ordering) ==============================*/
  {
    id:'q5', category:'logic', difficulty:1,
    modality:'text', render:'text',
    prompt:'A is taller than B. C is taller than A. Who is the tallest?',
    payload:{},
    options:[
      {id:'a', label:'A'},
      {id:'b', label:'B'},
      {id:'c', label:'C'},
      {id:'d', label:'Cannot be determined'}
    ],
    correct:'c',
    explanation:'C > A > B ka chain banega. Isliye C sabse taller.',
    skills:['logic'], timeLimit:20
  },

  /* === Q6 — EASY · MATRIX (rotation progression) =============================
     Each row rotates the shape +45°. */
  {
    id:'q6', category:'pattern', difficulty:1,
    modality:'visual', render:'matrix',
    prompt:'Complete the grid.',
    payload:{
      rows:3, cols:3,
      cells:[
        {kind:'triangle', rot:0},   {kind:'triangle', rot:45},   {kind:'triangle', rot:90},
        {kind:'triangle', rot:45},  {kind:'triangle', rot:90},   {kind:'triangle', rot:135},
        {kind:'triangle', rot:90},  {kind:'triangle', rot:135},  {blank:true}
      ]
    },
    options:[
      {id:'a', spec:{kind:'triangle', rot:180}},
      {id:'b', spec:{kind:'triangle', rot:90}},
      {id:'c', spec:{kind:'triangle', rot:45}},
      {id:'d', spec:{kind:'triangle', rot:0}}
    ],
    correct:'a',
    explanation:'Har row & column mein +45° rotation. Last cell = 180°.',
    skills:['pattern','spatial'], timeLimit:22
  },

  /* === Q7 — EASY · SPEED / MEMORY WARMUP · working memory (short digit span) */
  {
    id:'q7', category:'memory', difficulty:1,
    modality:'text', render:'memory',
    prompt:'Memorize these numbers. Then answer.',
    payload:{
      memoryDurationMs:3500,
      memoryContent:'3   8   1   5',
      question:'What was the SUM of the 2nd and 4th numbers?'
    },
    options:[
      {id:'a', label:'8'},
      {id:'b', label:'11'},
      {id:'c', label:'13'},
      {id:'d', label:'9'}
    ],
    correct:'c',
    explanation:'2nd = 8, 4th = 5, sum = 13. Working memory ka classic test.',
    skills:['memory'], timeLimit:20
  },

  /* === Q8 — EASY · SEQUENCE (count +1 per step) ==============================*/
  {
    id:'q8', category:'pattern', difficulty:1,
    modality:'visual', render:'sequence',
    prompt:'Find the next tile in the pattern.',
    payload:{
      cells:[
        {kind:'diamond', count:1}, {kind:'diamond', count:2},
        {kind:'diamond', count:3}, {kind:'diamond', count:4}, {blank:true}
      ]
    },
    options:[
      {id:'a', spec:{kind:'diamond', count:4}},
      {id:'b', spec:{kind:'diamond', count:6}},
      {id:'c', spec:{kind:'diamond', count:5}},
      {id:'d', spec:{kind:'diamond', count:3}}
    ],
    correct:'c',
    explanation:'Har step +1 diamond. 4 ke baad 5.',
    skills:['pattern'], timeLimit:20
  },

  /* === Q9 — MEDIUM · MATRIX (two-rule: count in row, kind in col) ============
     Row: count +1 · Col: shape shifts (circle→square→triangle). */
  {
    id:'q9', category:'pattern', difficulty:2,
    modality:'visual', render:'matrix',
    prompt:'Complete the grid. Two rules combine here.',
    payload:{
      rows:3, cols:3,
      cells:[
        {kind:'circle',  count:1}, {kind:'circle',  count:2}, {kind:'circle',  count:3},
        {kind:'square',  count:1}, {kind:'square',  count:2}, {kind:'square',  count:3},
        {kind:'triangle',count:1}, {kind:'triangle',count:2}, {blank:true}
      ]
    },
    options:[
      {id:'a', spec:{kind:'triangle', count:3}},
      {id:'b', spec:{kind:'triangle', count:4}},
      {id:'c', spec:{kind:'square',   count:3}},
      {id:'d', spec:{kind:'circle',   count:3}}
    ],
    correct:'a',
    explanation:'Row = same shape, count +1 per column. Column 3 mein count=3. Row 3 shape = triangle.',
    skills:['pattern','logic'], timeLimit:30
  },

  /* === Q10 — MEDIUM · SPATIAL (mental rotation of a fixed shape) =============
     The reference is asymmetric so rotations look different. */
  {
    id:'q10', category:'spatial', difficulty:2,
    modality:'visual', render:'rotation',
    prompt:'Which option is the SAME shape, just rotated (not mirrored)?',
    payload:{
      target:{kind:'l-shape', rot:0}
    },
    options:[
      {id:'a', spec:{kind:'l-shape', rot:90}},
      {id:'b', spec:{kind:'l-shape', rot:0, mirror:true}},
      {id:'c', spec:{kind:'l-shape', rot:45, mirror:true}},
      {id:'d', spec:{kind:'l-shape', rot:90, mirror:true}}
    ],
    correct:'a',
    explanation:'Sirf option A pure rotation hai (90°). Baki sab mein mirror flip bhi hai.',
    skills:['spatial'], timeLimit:30
  },

  /* === Q11 — MEDIUM · SEQUENCE (rotation +45° AND count +1) ==================*/
  {
    id:'q11', category:'pattern', difficulty:2,
    modality:'visual', render:'sequence',
    prompt:'Find the next step.',
    payload:{
      cells:[
        {kind:'arrow', rot:0,  count:1},
        {kind:'arrow', rot:45, count:2},
        {kind:'arrow', rot:90, count:3},
        {kind:'arrow', rot:135,count:4},
        {blank:true}
      ]
    },
    options:[
      {id:'a', spec:{kind:'arrow', rot:180, count:5}},
      {id:'b', spec:{kind:'arrow', rot:180, count:4}},
      {id:'c', spec:{kind:'arrow', rot:135, count:5}},
      {id:'d', spec:{kind:'arrow', rot:225, count:5}}
    ],
    correct:'a',
    explanation:'Do rules combine: +45° rotation aur +1 count per step. 135°+45°=180°, count=5.',
    skills:['pattern','spatial'], timeLimit:32
  },

  /* === Q12 — MEDIUM · LOGIC (seating with constraints) =======================*/
  {
    id:'q12', category:'logic', difficulty:2,
    modality:'text', render:'text',
    prompt:'5 friends sit in a row. Ali is at position 2 from left AND position 4 from right. How many friends total?',
    payload:{},
    options:[
      {id:'a', label:'4'},
      {id:'b', label:'5'},
      {id:'c', label:'6'},
      {id:'d', label:'7'}
    ],
    correct:'b',
    explanation:'Left se 2 + right se 4 − 1 (double count) = 5 log.',
    skills:['logic'], timeLimit:28
  },

  /* === Q13 — MEDIUM · MATRIX (color/shade progression) =======================*/
  {
    id:'q13', category:'pattern', difficulty:2,
    modality:'visual', render:'matrix',
    prompt:'Complete the pattern (look at fill).',
    payload:{
      rows:3, cols:3,
      cells:[
        {kind:'circle', fill:'none'},     {kind:'circle', fill:'#CBD5E1'}, {kind:'circle', fill:'#7C3AED'},
        {kind:'square', fill:'none'},     {kind:'square', fill:'#CBD5E1'}, {kind:'square', fill:'#7C3AED'},
        {kind:'triangle', fill:'none'},   {kind:'triangle', fill:'#CBD5E1'},{blank:true}
      ]
    },
    options:[
      {id:'a', spec:{kind:'triangle', fill:'#7C3AED'}},
      {id:'b', spec:{kind:'triangle', fill:'#CBD5E1'}},
      {id:'c', spec:{kind:'triangle', fill:'none'}},
      {id:'d', spec:{kind:'square',   fill:'#7C3AED'}}
    ],
    correct:'a',
    explanation:'Har row mein fill progression: none → light → dark. Row 3 shape = triangle, column 3 fill = dark.',
    skills:['pattern'], timeLimit:30
  },

  /* === Q14 — MEDIUM · LOGIC (conditional deduction) ==========================*/
  {
    id:'q14', category:'logic', difficulty:2,
    modality:'text', render:'text',
    prompt:'If it rains, the ground gets wet. The ground is NOT wet. Which conclusion is valid?',
    payload:{},
    options:[
      {id:'a', label:'It rained.'},
      {id:'b', label:'It did not rain.'},
      {id:'c', label:'Cannot say anything.'},
      {id:'d', label:'It will rain later.'}
    ],
    correct:'b',
    explanation:'Modus tollens: "P → Q" aur "not Q" → "not P". Ground wet nahi, isliye rain nahi hui.',
    skills:['logic'], timeLimit:28
  },

  /* === Q15 — MEDIUM · SEQUENCE (element add/remove) ==========================*/
  {
    id:'q15', category:'pattern', difficulty:2,
    modality:'visual', render:'sequence',
    prompt:'What comes next?',
    payload:{
      cells:[
        {multi:[{kind:'circle', size:0.9}]},
        {multi:[{kind:'circle', size:0.9},{kind:'square', size:0.55}]},
        {multi:[{kind:'circle', size:0.9},{kind:'square', size:0.55},{kind:'dot'}]},
        {multi:[{kind:'circle', size:0.9},{kind:'square', size:0.55},{kind:'dot'},{kind:'cross', size:0.4}]},
        {blank:true}
      ]
    },
    options:[
      {id:'a', spec:{multi:[{kind:'circle', size:0.9},{kind:'square', size:0.55},{kind:'dot'},{kind:'cross', size:0.4},{kind:'star', size:0.35}]}},
      {id:'b', spec:{multi:[{kind:'circle', size:0.9},{kind:'square', size:0.55},{kind:'dot'}]}},
      {id:'c', spec:{multi:[{kind:'circle', size:0.9},{kind:'dot'}]}},
      {id:'d', spec:{multi:[{kind:'circle', size:0.9},{kind:'square', size:0.55},{kind:'cross', size:0.4}]}}
    ],
    correct:'a',
    explanation:'Har step mein ek naya element add ho raha hai. Next mein 5 layers.',
    skills:['pattern','logic'], timeLimit:30
  },

  /* === Q16 — MEDIUM · WORKING MEMORY (shape sequence reverse) ================*/
  {
    id:'q16', category:'memory', difficulty:2,
    modality:'text', render:'memory',
    prompt:'Memorize the sequence, then answer.',
    payload:{
      memoryDurationMs:4000,
      memoryContent:'▲   ●   ■   ◆   ★',
      question:'Which shape was in the MIDDLE (3rd position)?'
    },
    options:[
      {id:'a', label:'▲'},
      {id:'b', label:'●'},
      {id:'c', label:'■'},
      {id:'d', label:'◆'}
    ],
    correct:'c',
    explanation:'Sequence: ▲ ● ■ ◆ ★ → 3rd position = ■ (square).',
    skills:['memory'], timeLimit:20
  },

  /* === Q17 — MEDIUM · NUMBER LOGIC (look-and-say encoding) ==================*/
  {
    id:'q17', category:'logic', difficulty:2,
    modality:'text', render:'text',
    prompt:'Look-and-say sequence: 1, 11, 21, 1211, 111221, ?',
    payload:{},
    options:[
      {id:'a', label:'312211'},
      {id:'b', label:'1112221'},
      {id:'c', label:'211311'},
      {id:'d', label:'112132'}
    ],
    correct:'a',
    explanation:'Har term previous ko describe karta hai. 111221 = "three 1s, two 2s, one 1" → 312211.',
    skills:['logic','pattern'], timeLimit:35
  },

  /* === Q18 — MEDIUM · SPATIAL (paper fold + punch) ===========================*/
  {
    id:'q18', category:'spatial', difficulty:2,
    modality:'visual', render:'paperfold',
    prompt:'A square paper is folded in half vertically, then a hole is punched near the top edge (of the folded half). When unfolded, where are the holes?',
    payload:{
      folds:['V'],
      punchAt:[[0.5, 0.15]]     /* on the folded rectangle, centered top */
    },
    options:[
      {id:'a', holes:['0,0']},
      {id:'b', holes:['0,0','0,1']},
      {id:'c', holes:['1,0','1,1']},
      {id:'d', holes:['0,0','1,1']}
    ],
    correct:'b',
    explanation:'Ek fold = 2 layers → 2 holes. Fold vertical tha isliye holes horizontally symmetric aayenge, top row mein.',
    skills:['spatial'], timeLimit:35
  },

  /* === Q19 — HARD · MATRIX (XOR / superposition rule) ========================
     Cell3 in each row = shapes that appear in cell1 XOR cell2 (i.e. not both). */
  {
    id:'q19', category:'pattern', difficulty:3,
    modality:'visual', render:'matrix',
    prompt:'Each row combines cells by XOR (shapes shared by BOTH disappear). Find the missing tile.',
    payload:{
      rows:3, cols:3,
      cells:[
        /* Row 1: {C,S} XOR {S,T} = {C,T} */
        {multi:[{kind:'circle', size:0.7, rot:0, stroke:'#0F172A'},{kind:'square', size:0.45}]},
        {multi:[{kind:'square', size:0.7},{kind:'triangle', size:0.45}]},
        {multi:[{kind:'circle', size:0.7},{kind:'triangle', size:0.45}]},
        /* Row 2: {S,T} XOR {C,T} = {S,C} */
        {multi:[{kind:'square', size:0.7},{kind:'triangle', size:0.45}]},
        {multi:[{kind:'circle', size:0.7},{kind:'triangle', size:0.45}]},
        {multi:[{kind:'square', size:0.7},{kind:'circle', size:0.45}]},
        /* Row 3: {C,T} XOR {S,C} = {T,S} → ? */
        {multi:[{kind:'circle', size:0.7},{kind:'triangle', size:0.45}]},
        {multi:[{kind:'square', size:0.7},{kind:'circle', size:0.45}]},
        {blank:true}
      ]
    },
    options:[
      {id:'a', spec:{multi:[{kind:'triangle', size:0.7},{kind:'square', size:0.45}]}},
      {id:'b', spec:{multi:[{kind:'circle', size:0.7},{kind:'square', size:0.45}]}},
      {id:'c', spec:{multi:[{kind:'triangle', size:0.7},{kind:'circle', size:0.45}]}},
      {id:'d', spec:{multi:[{kind:'circle', size:0.7},{kind:'triangle', size:0.45}]}}
    ],
    correct:'a',
    explanation:'XOR rule: har row mein cell3 = cell1 aur cell2 ke UNIQUE shapes (jo dono mein common hai wo hat gaya). Row 3: {C,T} XOR {S,C} = {T,S}.',
    skills:['pattern','logic'], timeLimit:45
  },

  /* === Q20 — HARD · SPATIAL (cube net → folded cube) =========================
     Net has labels 1..6 on the cross. Which folded cube matches? */
  {
    id:'q20', category:'spatial', difficulty:3,
    modality:'visual', render:'cubenet',
    prompt:'When this net is folded into a cube, which cube is correct?',
    payload:{
      /* Positions: top, left, front, right, back, bottom */
      faceLabels:['1','2','3','4','5','6']
    },
    options:[
      /* When folded from a standard cross with front=3: visible faces from the
         normal 3/4 view are front=3, right=4, top=1. So option A is correct. */
      {id:'a', cube:{top:'1', left:'3', right:'4'}},
      {id:'b', cube:{top:'6', left:'3', right:'4'}},
      {id:'c', cube:{top:'1', left:'2', right:'4'}},
      {id:'d', cube:{top:'1', left:'3', right:'5'}}
    ],
    correct:'a',
    explanation:'Cross-net fold karo: top face=1, front=3, right=4. Bottom=6 hoga (top ke opposite), left=2, back=5. Isometric view mein hum top, front (as left), right dekh rahe hain → 1,3,4.',
    skills:['spatial'], timeLimit:45
  },

  /* === Q21 — HARD · INSIGHT (3 switches, 3 bulbs) ============================*/
  {
    id:'q21', category:'logic', difficulty:3,
    modality:'text', render:'text',
    prompt:'3 switches control 3 bulbs in a closed room. You can flip switches freely, but you can enter the room only ONCE. How do you find which switch controls which bulb?',
    payload:{},
    options:[
      {id:'a', label:'Flip all 3 on, then enter — the brightest one is switch 1.'},
      {id:'b', label:'Flip switch 1 ON for 5 min, then OFF. Flip switch 2 ON. Enter. Bulb ON = 2, bulb OFF but WARM = 1, bulb OFF and cold = 3.'},
      {id:'c', label:'Flip switches one by one and listen for a click.'},
      {id:'d', label:'It is impossible with only one entry.'}
    ],
    correct:'b',
    explanation:'Heat ko as a 3rd signal use karo. ON = switch 2. OFF+warm = switch 1 (recently on). OFF+cold = switch 3. Ek entry mein tino identify.',
    skills:['logic'], timeLimit:45
  },

  /* === Q22 — HARD · SEQUENCE (2-rule abstract: rotation +90° AND fill toggle)*/
  {
    id:'q22', category:'pattern', difficulty:3,
    modality:'visual', render:'sequence',
    prompt:'Two rules apply. Find the next tile.',
    payload:{
      cells:[
        {kind:'triangle', rot:0,   fill:'none'},
        {kind:'triangle', rot:90,  fill:'#7C3AED'},
        {kind:'triangle', rot:180, fill:'none'},
        {kind:'triangle', rot:270, fill:'#7C3AED'},
        {blank:true}
      ]
    },
    options:[
      {id:'a', spec:{kind:'triangle', rot:0,   fill:'none'}},
      {id:'b', spec:{kind:'triangle', rot:90,  fill:'#7C3AED'}},
      {id:'c', spec:{kind:'triangle', rot:0,   fill:'#7C3AED'}},
      {id:'d', spec:{kind:'triangle', rot:270, fill:'none'}}
    ],
    correct:'a',
    explanation:'Rule 1: +90° rotation → 270°+90° = 360° = 0°. Rule 2: fill alternates none/dark → next = none. Combined = 0°, none.',
    skills:['pattern','spatial'], timeLimit:40
  },

  /* === Q23 — BOSS · LOGIC (seating chain) ==================================*/
  {
    id:'q23', category:'logic', difficulty:3,
    modality:'text', render:'text',
    prompt:'Five friends sit in a row. Q is at the left end. To Q\'s right sit P, then R, then S, then T (in that order). Which position does S occupy?',
    payload:{},
    options:[
      {id:'a', label:'Position 2'},
      {id:'b', label:'Position 3'},
      {id:'c', label:'Position 4'},
      {id:'d', label:'Position 5'}
    ],
    correct:'c',
    explanation:'Left to right: Q(1), P(2), R(3), S(4), T(5). Isliye S = position 4.',
    skills:['logic'], timeLimit:45
  },

  /* === Q24 — BOSS · MATRIX (advanced two-rule 3x3) ===========================
     Row rule: kind cycles (C→S→T). Col rule: size grows (small→med→large).
     Missing cell (r=2,c=2) → Triangle, large. */
  {
    id:'q24', category:'pattern', difficulty:3,
    modality:'visual', render:'matrix',
    prompt:'Two rules govern this grid (one by row, one by column). Complete it.',
    payload:{
      rows:3, cols:3,
      cells:[
        {kind:'circle',   size:0.5}, {kind:'circle',   size:0.75}, {kind:'circle',   size:1.0},
        {kind:'square',   size:0.5}, {kind:'square',   size:0.75}, {kind:'square',   size:1.0},
        {kind:'triangle', size:0.5}, {kind:'triangle', size:0.75}, {blank:true}
      ]
    },
    options:[
      {id:'a', spec:{kind:'triangle', size:1.0}},
      {id:'b', spec:{kind:'triangle', size:0.75}},
      {id:'c', spec:{kind:'square',   size:1.0}},
      {id:'d', spec:{kind:'triangle', size:0.5}}
    ],
    correct:'a',
    explanation:'Row rule = shape (row3 = triangle). Column rule = size (col3 = large). Missing = large triangle.',
    skills:['pattern','logic','spatial'], timeLimit:45
  },

  /* === Q25 — BOSS · SPATIAL (mental rotation + count) ========================*/
  {
    id:'q25', category:'spatial', difficulty:3,
    modality:'visual', render:'sequence',
    prompt:'The final "boss" puzzle. Which tile continues both rules?',
    payload:{
      cells:[
        {kind:'l-shape', rot:0,   count:1},
        {kind:'l-shape', rot:90,  count:1},
        {kind:'l-shape', rot:180, count:1},
        {kind:'l-shape', rot:270, count:1},
        {blank:true}
      ]
    },
    options:[
      {id:'a', spec:{kind:'l-shape', rot:0,   count:1}},
      {id:'b', spec:{kind:'l-shape', rot:45,  count:1}},
      {id:'c', spec:{kind:'l-shape', rot:90,  count:1}},
      {id:'d', spec:{kind:'l-shape', rot:180, count:1}}
    ],
    correct:'a',
    explanation:'Rotation cycle 0°→90°→180°→270°→(360°=0°). Isliye wapas original orientation.',
    skills:['spatial','pattern'], timeLimit:40
  }

];

/* Sanity: production build is guaranteed to have 25 questions. Anything else
 * is a data-authoring bug we want to catch loudly. */
if (IQ_QUESTIONS.length !== 25 && typeof console !== 'undefined') {
  /* eslint-disable no-console */
  console.warn('[iqtest] question count is', IQ_QUESTIONS.length, '- expected 25');
}

/* ============================================================================
 *  SECTION 3 — MAIN GAME
 * ============================================================================ */
function playIQTest(body, setScore, end, wrap, startClock){

  /* -------- state -------- */
  const state = {
    qi:0,
    totalPts:0,
    streak:0,
    bestStreak:0,
    skipsLeft:1,
    results:[],           /* [{id,cat,diff,correct,timedOut,elapsedMs,limit}] */
    timer:null,
    timerHandle:null,
    onboarded: !!S('nz_iq_onboard'),
    cbSafe: !!S('nz_iq_cbsafe')
  };
  const bestIQ = S('nz_iq_best') || 0;

  /* keyboard shortcut listener — attached only during a live question */
  let kbdHandler = null;
  const detachKbd = ()=>{ if(kbdHandler){ document.removeEventListener('keydown', kbdHandler); kbdHandler=null; } };

  /* cleanup when the host wraps up the game */
  function _cleanup(){
    if(state.timer){ _cti(state.timer); state.timer=null; }
    detachKbd();
  }
  wrap.addEventListener('remove_game', _cleanup);

  /* -------- top-level container so styles are scoped -------- */
  const root = $('<div class="iq5 iq-host"></div>');
  body.appendChild(root);

  /* -------- ONBOARDING (first play only) -------- */
  function showOnboarding(){
    root.innerHTML =
      '<div class="iq5-onb">'+
        '<div class="iq5-onb-hero">'+
          '<div class="iq5-onb-emoji">🧠</div>'+
          '<h2>Cognitive Assessment</h2>'+
          '<p class="iq5-onb-sub">25 puzzles · science-grade scoring</p>'+
          (bestIQ ? '<div class="iq5-best-chip">🏆 Your Best IQ: '+bestIQ+' · '+iqClassify(bestIQ).label+'</div>' : '')+
        '</div>'+
        '<div class="iq5-onb-cards">'+
          '<div class="iq5-onb-card"><div class="iq5-onb-ico">🖼️</div><div><b>Mostly visual</b><div>Find the hidden rule — no vocab, no formulas.</div></div></div>'+
          '<div class="iq5-onb-card"><div class="iq5-onb-ico">📈</div><div><b>Difficulty rises</b><div>Harder puzzles = more time & more points.</div></div></div>'+
          '<div class="iq5-onb-card"><div class="iq5-onb-ico">⏭️</div><div><b>1 free skip</b><div>Stuck? Skip once — costs a few points.</div></div></div>'+
        '</div>'+
        '<label class="iq5-onb-toggle"><input type="checkbox" id="iqCbToggle" '+(state.cbSafe?'checked':'')+'/> <span>Colorblind-safe palette</span></label>'+
        '<button class="btn-primary iq5-onb-cta" id="iqOnbGo">Begin Assessment ▶</button>'+
        (bestIQ ? '<button class="iq5-link" id="iqOnbSkip">Skip intro</button>' : '')+
      '</div>';

    const cb = root.querySelector('#iqCbToggle');
    cb.addEventListener('change', ()=>{
      state.cbSafe = cb.checked;
      try{ setS('nz_iq_cbsafe', cb.checked ? 1 : 0); }catch(e){}
    });
    root.querySelector('#iqOnbGo').addEventListener('click', ()=>{
      try{ setS('nz_iq_onboard', 1); }catch(e){}
      state.onboarded=true;
      startTest();
    });
    const skip = root.querySelector('#iqOnbSkip');
    if(skip) skip.addEventListener('click', startTest);
  }

  /* -------- START the actual test -------- */
  function startTest(){
    if(startClock) startClock();
    state.qi=0;
    renderQuestion();
  }

  /* --------------------------- QUESTION RENDER --------------------------- */
  function renderQuestion(){
    detachKbd();
    if(state.qi >= IQ_QUESTIONS.length){ finishTest(); return; }

    const q = IQ_QUESTIONS[state.qi];
    const diffLabel = q.difficulty===1 ? 'Easy' : q.difficulty===2 ? 'Medium' : 'Hard';
    const catInfo = IQ_CATS[q.category] || IQ_CATS.pattern;

    /* Difficulty ribbon: fill dots up to q.difficulty */
    const ribbon = '<span class="iq5-ribbon">'+
      [1,2,3,4,5].map(i=>{
        const on = (i <= Math.round(state.qi/25*5+0.5)); /* rough position along the curve */
        return '<span class="iq5-ribbon-dot '+(on?'on':'')+'"></span>';
      }).join('')+
    '</span>';

    const dots = Array.from({length: IQ_QUESTIONS.length}, (_,i)=>{
      if(i < state.qi) return '<span class="iq5-dot iq5-dot-done"></span>';
      if(i === state.qi) return '<span class="iq5-dot iq5-dot-active"></span>';
      return '<span class="iq5-dot"></span>';
    }).join('');

    root.innerHTML =
      '<div class="iq5-play">'+
        '<div class="iq5-hud">'+
          '<div class="iq5-qmeta">'+
            '<span class="iq5-cat" style="background:'+catInfo.color+'22;color:'+catInfo.color+';border:1px solid '+catInfo.color+'55;">'+catInfo.label+'</span>'+
            '<span class="iq5-diff iq5-diff-'+q.difficulty+'">'+diffLabel+'</span>'+
          '</div>'+
          '<div class="iq5-qcount">Q '+(state.qi+1)+' <span>/ '+IQ_QUESTIONS.length+'</span></div>'+
        '</div>'+
        '<div class="iq5-dotrow">'+dots+'</div>'+
        '<div class="iq5-curve">Easy '+ribbon+' Hard</div>'+
        '<div class="iq5-timer-wrap" id="iqTimerHost"></div>'+
        '<div class="iq5-qcard iq5-anim-in">'+
          '<div class="iq5-prompt">'+q.prompt+'</div>'+
          '<div class="iq5-visual" id="iqVisual"></div>'+
        '</div>'+
        '<div class="iq5-opts" id="iqOpts"></div>'+
        '<div class="iq5-actions">'+
          '<button class="iq5-skip" id="iqSkipBtn" '+(state.skipsLeft?'':'disabled')+'>⏭ Skip ('+state.skipsLeft+' left)</button>'+
        '</div>'+
        '<div class="iq5-fx" id="iqFx" aria-live="polite"></div>'+
      '</div>';

    /* Render the timer ring */
    const ring = IQ_makeTimerRing(58);
    root.querySelector('#iqTimerHost').appendChild(ring.el);

    /* Render the question visual + options based on `render` type */
    const visual = root.querySelector('#iqVisual');
    const optsEl = root.querySelector('#iqOpts');

    /* memory type has 2 phases: memorize → question. */
    if(q.render === 'memory'){
      renderMemoryPhase(q, ring, visual, optsEl);
    }else{
      renderVisualAndOptions(q, visual, optsEl);
      startTimer(q, ring, ()=> onAnswer(q, null, true, ring.currentElapsed()));
    }

    /* Skip button */
    const skipBtn = root.querySelector('#iqSkipBtn');
    skipBtn.addEventListener('click', ()=>{
      if(state.skipsLeft <= 0) return;
      state.skipsLeft--;
      onAnswer(q, '__skip__', false, ring.currentElapsed());
    });

    /* Keyboard shortcuts: A/B/C/D or 1..4 select; Enter uses focused option. */
    kbdHandler = (ev)=>{
      const k = (ev.key||'').toLowerCase();
      const map = {a:0,b:1,c:2,d:3,'1':0,'2':1,'3':2,'4':3};
      if(map[k] != null){
        const btn = optsEl.querySelectorAll('.iq5-opt')[map[k]];
        if(btn && !btn.disabled) btn.click();
      }
    };
    document.addEventListener('keydown', kbdHandler);
  }

  /* ---------------- MEMORY PHASE ---------------- */
  function renderMemoryPhase(q, ring, visualEl, optsEl){
    visualEl.innerHTML =
      '<div class="iq5-mem-phase">'+
        '<div class="iq5-mem-label">🧠 Memorize this</div>'+
        '<div class="iq5-mem-content">'+q.payload.memoryContent+'</div>'+
        '<div class="iq5-mem-progress"><span id="iqMemBar"></span></div>'+
      '</div>';
    optsEl.innerHTML = '';
    /* Timer ring counts memorize duration too */
    const dur = q.payload.memoryDurationMs || 3500;
    const start = Date.now();
    const memBar = visualEl.querySelector('#iqMemBar');
    if(state.timer){ _cti(state.timer); }
    state.timer = _si(()=>{
      const el = Date.now()-start;
      const frac = Math.max(0, 1 - el/dur);
      const secs = Math.max(0, (dur - el)/1000);
      ring.set(frac, secs);
      if(memBar) memBar.style.width = (100*el/dur)+'%';
      if(el >= dur){
        _cti(state.timer); state.timer=null;
        memBar && (memBar.style.width='100%');
        /* switch to question phase */
        visualEl.innerHTML = '<div class="iq5-mem-question">'+q.payload.question+'</div>';
        renderTextOptions(q, optsEl);
        startTimer(q, ring, ()=> onAnswer(q, null, true, ring.currentElapsed()));
      }
    }, 40);
    ring.currentElapsed = ()=> 0; /* placeholder, overwritten by startTimer */
  }

  /* ---------------- VISUAL + OPTIONS ---------------- */
  function renderVisualAndOptions(q, visualEl, optsEl){
    const r = q.render;
    if(r==='matrix'){
      visualEl.innerHTML = IQ_drawMatrix(q.payload.rows, q.payload.cols, q.payload.cells);
      renderVisualOptions(q, optsEl);
    }else if(r==='sequence'){
      visualEl.innerHTML = IQ_drawSequence(q.payload.cells);
      renderVisualOptions(q, optsEl);
    }else if(r==='rotation' || r==='mirror'){
      const spec = Object.assign({}, q.payload.target);
      visualEl.innerHTML =
        '<div class="iq5-target">'+
          IQ_optionTile(spec)+
          '<div class="iq5-target-label">Target</div>'+
        '</div>';
      renderVisualOptions(q, optsEl, /*mirrorSupport*/ true);
    }else if(r==='cubenet'){
      visualEl.innerHTML = IQ_drawCubeNet(q.payload.faceLabels);
      /* options are folded cubes */
      optsEl.innerHTML = q.options.map((o,i)=>optionButton(
        i, o.id, IQ_drawFoldedCube(o.cube)
      )).join('');
      attachOptClicks(q, optsEl);
    }else if(r==='paperfold'){
      visualEl.innerHTML = IQ_drawFoldSteps(q.payload.folds, q.payload.punchAt);
      optsEl.innerHTML = q.options.map((o,i)=>{
        const set = new Set(o.holes||[]);
        return optionButton(i, o.id, IQ_drawUnfolded(set));
      }).join('');
      attachOptClicks(q, optsEl);
    }else{
      /* pure text */
      visualEl.innerHTML = '';
      visualEl.style.display = 'none';
      renderTextOptions(q, optsEl);
    }
  }

  function renderVisualOptions(q, optsEl, mirrorSupport){
    optsEl.innerHTML = q.options.map((o,i)=>{
      /* mirror flag: wrap the tile in a container with a horizontal flip */
      const tile = IQ_optionTile(o.spec);
      const inner = (mirrorSupport && o.spec && o.spec.mirror)
        ? '<div class="iq5-mirror">'+tile+'</div>'
        : tile;
      return optionButton(i, o.id, inner);
    }).join('');
    attachOptClicks(q, optsEl);
  }

  function renderTextOptions(q, optsEl){
    optsEl.innerHTML = q.options.map((o,i)=>optionButton(i, o.id, '<span class="iq5-opt-text">'+o.label+'</span>')).join('');
    attachOptClicks(q, optsEl);
  }

  function optionButton(i, id, inner){
    const letter = String.fromCharCode(65+i);
    return '<button class="iq5-opt" data-id="'+id+'" data-i="'+i+'" aria-label="Option '+letter+'">'+
             '<span class="iq5-opt-letter">'+letter+'</span>'+
             '<span class="iq5-opt-body">'+inner+'</span>'+
           '</button>';
  }

  function attachOptClicks(q, optsEl){
    optsEl.querySelectorAll('.iq5-opt').forEach(btn=>{
      btn.addEventListener('click', ()=>{
        if(btn.disabled) return;
        const chosen = btn.getAttribute('data-id');
        const elapsed = state.timerHandle ? state.timerHandle.elapsed() : 0;
        onAnswer(q, chosen, false, elapsed);
      });
    });
  }

  /* ---------------- TIMER ---------------- */
  function startTimer(q, ring, onExpire){
    const limitMs = (q.timeLimit || 25) * 1000;
    if(state.timer){ _cti(state.timer); }
    const t0 = Date.now();
    let elapsed = 0;
    state.timerHandle = { elapsed: ()=> elapsed };
    ring.currentElapsed = ()=> elapsed;
    state.timer = _si(()=>{
      elapsed = Date.now() - t0;
      const frac = Math.max(0, 1 - elapsed/limitMs);
      const secs = Math.max(0, (limitMs - elapsed)/1000);
      ring.set(frac, secs);
      if(elapsed >= limitMs){
        _cti(state.timer); state.timer=null;
        onExpire();
      }
    }, 100);
  }

  /* ---------------- ANSWER HANDLING ---------------- */
  function onAnswer(q, chosenId, timedOut, elapsedMs){
    if(state.timer){ _cti(state.timer); state.timer=null; }
    detachKbd();

    const skipped = chosenId === '__skip__';
    const isCorrect = !timedOut && !skipped && (chosenId === q.correct);

    /* Update result log */
    const limitMs = (q.timeLimit || 25) * 1000;
    state.results.push({
      id:q.id, cat:q.category, diff:q.difficulty,
      correct:isCorrect, timedOut:!!timedOut, skipped:!!skipped,
      elapsedMs, limitMs, skills:q.skills||[]
    });

    /* Scoring — see documented mapping in finishTest() */
    let pts = 0;
    if(isCorrect){
      const base = q.difficulty * 10;                   /* 10 / 20 / 30 */
      const timeRatio = elapsedMs / limitMs;
      const speed = timeRatio < 0.35 ? 1.5
                  : timeRatio < 0.60 ? 1.25
                  : timeRatio < 0.85 ? 1.0
                  : 0.85;                               /* slow-but-correct floor */
      const streakMult = 1 + Math.min(0.4, state.streak * 0.08);
      pts = Math.round(base * speed * streakMult);
      state.streak++;
      state.bestStreak = Math.max(state.bestStreak, state.streak);
    }else{
      state.streak = 0;
      if(skipped) pts = -5;                             /* small skip penalty */
    }
    state.totalPts += pts;
    setScore(Math.max(0, state.totalPts));

    /* Visual feedback on the option buttons */
    root.querySelectorAll('.iq5-opt').forEach(b=>{
      b.disabled=true;
      const id = b.getAttribute('data-id');
      if(id === q.correct) b.classList.add('iq5-opt-correct');
      if(!isCorrect && !timedOut && !skipped && id === chosenId) b.classList.add('iq5-opt-wrong');
    });

    /* Sound + haptic + fx */
    try{
      if(isCorrect){ playSound('correct'); haptic(15); }
      else         { playSound('wrong');   haptic([20,40,20]); }
    }catch(e){}

    /* Feedback panel with explanation */
    const fx = root.querySelector('#iqFx');
    if(fx){
      const badge = isCorrect
        ? '<span class="iq5-fx-badge iq5-fx-ok">✓ Correct  +'+pts+' pts</span>'
        : timedOut
          ? '<span class="iq5-fx-badge iq5-fx-time">⏰ Time up</span>'
          : skipped
            ? '<span class="iq5-fx-badge iq5-fx-skip">⏭ Skipped</span>'
            : '<span class="iq5-fx-badge iq5-fx-bad">✕ Not quite</span>';
      fx.innerHTML =
        '<div class="iq5-explain">'+
          '<div class="iq5-explain-head">'+badge+'</div>'+
          '<div class="iq5-explain-body">💡 '+q.explanation+'</div>'+
          '<div class="iq5-explain-hint">tap to continue ▶</div>'+
        '</div>';
      const cont = ()=>{ nextQ(); };
      fx.addEventListener('click', cont, {once:true});
      /* auto-advance after 2.6s */
      _st(()=>{ if(root.contains(fx)) nextQ(); }, 2600);
    }else{
      _st(nextQ, 1800);
    }
  }

  function nextQ(){
    state.qi++;
    renderQuestion();
  }

  /* ============================================================================
   *  SECTION 4 — FINISH: IQ SCORE + RADAR + RESULTS SCREEN
   *  ---------------------------------------------------------------------------
   *  Scoring mapping (documented):
   *    - Each Q base = difficulty * 10
   *    - speed multiplier ∈ [0.85 .. 1.5]
   *    - streak multiplier ∈ [1.0 .. 1.4]
   *    - Total raw points → normalized to 0..1 via best-possible ceiling
   *    - Standard IQ score: mean 100, SD 15
   *        iq = round(75 + norm * 60)  clamp [70,145]
   *        (a norm of 0.5 → IQ 105; norm 1.0 → IQ 135; strong bonuses can nudge
   *         above 135 via streak + speed but hard-capped at 145.)
   *    - Percentile from a normal(100,15) bell curve.
   *    - 5 skill scores (Pattern, Spatial, Logic, Memory, Speed) derived from
   *      per-question `skills[]`: each correct answer contributes to every skill
   *      listed on that question; final = correct_sum / weighted_max.
   * ============================================================================ */
  function computeScores(){
    /* max possible pts (if all correct with best speed & max streak) */
    let bestPossible = 0;
    IQ_QUESTIONS.forEach((q,i)=>{
      const base = q.difficulty * 10;
      const streakMult = 1 + Math.min(0.4, i * 0.08); /* actually streak grows through the run */
      bestPossible += base * 1.5 * Math.min(1.4, streakMult);
    });
    /* Simpler ceiling estimate: sum of (base * 1.5 * 1.4) */
    const cap = IQ_QUESTIONS.reduce((s,q)=> s + q.difficulty*10*1.5*1.4, 0);
    const norm = IQ_clamp(state.totalPts / cap, 0, 1);
    let iq = Math.round(75 + norm * 60);
    iq = IQ_clamp(iq, 70, 145);

    /* Skill scoring */
    const skillTotals = { pattern:0, spatial:0, logic:0, memory:0, speed:0 };
    const skillMax    = { pattern:0, spatial:0, logic:0, memory:0, speed:0 };
    /* "Speed" skill: fraction of the time remaining on correct answers */
    let speedNumer=0, speedDenom=0;
    state.results.forEach((r,idx)=>{
      const q = IQ_QUESTIONS[idx];
      if(!q) return;
      (q.skills||[]).forEach(s=>{
        if(skillMax[s] == null){ skillMax[s]=0; skillTotals[s]=0; }
        skillMax[s] += q.difficulty;
        if(r.correct) skillTotals[s] += q.difficulty;
      });
      /* Speed skill = avg (1 - timeRatio) on correct answers */
      if(r.correct){
        const ratio = r.elapsedMs / r.limitMs;
        speedNumer += (1 - IQ_clamp(ratio, 0, 1));
        speedDenom += 1;
      }
    });
    const skills = {};
    ['pattern','spatial','logic','memory'].forEach(s=>{
      skills[s] = skillMax[s] ? skillTotals[s]/skillMax[s] : 0;
    });
    skills.speed = speedDenom ? speedNumer/speedDenom : 0;

    /* Accuracy + timing stats */
    const total = state.results.length;
    const correct = state.results.filter(r=>r.correct).length;
    const avgMs = total ? state.results.reduce((s,r)=>s+r.elapsedMs,0)/total : 0;

    return { iq, norm, cap, skills, correct, total, avgMs, bestStreak:state.bestStreak };
  }

  function pickTips(scores){
    /* Personalized 2-3 tips based on the skill radar. */
    const tips=[];
    const sorted = Object.entries(scores.skills).sort((a,b)=>a[1]-b[1]);
    const weakest = sorted[0], secondWeak = sorted[1];
    const strongest = sorted[sorted.length-1];

    const advice = {
      pattern:'Practice Raven-style matrices daily — spot count/rotation/size rules first.',
      spatial:'Play mental-rotation puzzles and paper-fold games to strengthen visualization.',
      logic  :'Try seating & syllogism puzzles — force yourself to draw the constraints on paper.',
      memory :'Do digit-span or N-back drills. Even 3 minutes a day rewires working memory.',
      speed  :'Push yourself to answer faster on the easy ones — leave time budget for the hard.'
    };
    if(weakest)     tips.push('🎯 Train more · '+cap1(weakest[0])+': '+advice[weakest[0]]);
    if(secondWeak && secondWeak[0] !== weakest[0]) tips.push('💡 Also work on '+cap1(secondWeak[0])+' — '+advice[secondWeak[0]].split(' — ')[0]);
    if(strongest)   tips.push('💪 Your strength · '+cap1(strongest[0])+' is above the rest. Lean on it in future tests.');
    return tips.slice(0,3);
  }
  function cap1(s){ return s.charAt(0).toUpperCase()+s.slice(1); }

  function finishTest(){
    _cleanup();
    const S1 = computeScores();
    const cls = iqClassify(S1.iq);
    const pctile = IQ_bellCurvePctile(S1.iq);
    const prevBest = S('nz_iq_best')||0;
    const newPB = S1.iq > prevBest;
    if(newPB){ try{ setS('nz_iq_best', S1.iq); }catch(e){} }
    try{
      setS('nz_iq_games', (S('nz_iq_games')||0)+1);
      setS('nz_iq_profile', { iq:S1.iq, pctile, skills:S1.skills, ts: Date.now() });
    }catch(e){}
    /* Confetti on high scores */
    try{ if(newPB || S1.iq >= 120) confetti(80); }catch(e){}

    /* Report the IQ score as the game's value (the host uses this for stars,
     * best-record, mastery, XP, achievements — same contract as before). */
    setScore(S1.iq);

    /* Build the results HTML using the host's endGame() opts.statsHtml slot */
    const p = IQ_palette();
    const strongest = Object.entries(S1.skills).sort((a,b)=>b[1]-a[1])[0];
    const weakest   = Object.entries(S1.skills).sort((a,b)=>a[1]-b[1])[0];
    const tips = pickTips(S1);

    const radar = IQ_drawRadar(S1.skills);

    const skillRows = ['pattern','spatial','logic','memory','speed'].map(k=>{
      const v = Math.round((S1.skills[k]||0)*100);
      const col = IQ_CATS[k] ? IQ_CATS[k].color : p.prim;
      return '<div class="iq5-skill-row">'+
        '<span class="iq5-skill-name" style="color:'+col+'">'+cap1(k)+'</span>'+
        '<span class="iq5-skill-bar"><span class="iq5-skill-fill" style="width:'+v+'%;background:'+col+'"></span></span>'+
        '<span class="iq5-skill-val">'+v+'%</span>'+
      '</div>';
    }).join('');

    /* Circular animated big-score gauge */
    const gPct = IQ_clamp((S1.iq-70)/(145-70), 0, 1);
    const circ = Math.round(2*Math.PI*52);
    const gauge =
      '<div class="iq5-gauge">'+
        '<svg width="170" height="170" viewBox="0 0 120 120" class="iq5-gauge-svg">'+
          '<circle cx="60" cy="60" r="52" fill="none" stroke="var(--border)" stroke-width="10"/>'+
          '<circle id="iqGaugeArc" cx="60" cy="60" r="52" fill="none" stroke="url(#iqGaugeG)" stroke-width="10" stroke-linecap="round" '+
            'stroke-dasharray="'+circ+'" stroke-dashoffset="'+circ+'" transform="rotate(-90 60 60)"/>'+
          '<defs><linearGradient id="iqGaugeG" x1="0" y1="0" x2="1" y2="1">'+
            '<stop offset="0" stop-color="'+cls.color+'"/>'+
            '<stop offset="1" stop-color="#34D399"/>'+
          '</linearGradient></defs>'+
        '</svg>'+
        '<div class="iq5-gauge-inner">'+
          '<div class="iq5-gauge-num" id="iqGaugeNum">0</div>'+
          '<div class="iq5-gauge-lbl">IQ SCORE</div>'+
        '</div>'+
      '</div>';

    const shareCard =
      '<div class="iq5-share-card" id="iqShareCard">'+
        '<div class="iq5-share-brand">NeuroZen · Cognitive Test</div>'+
        '<div class="iq5-share-score" style="color:'+cls.color+'">'+S1.iq+'</div>'+
        '<div class="iq5-share-label">'+cls.label+' · Top '+(100-pctile)+'%</div>'+
        '<div class="iq5-share-radar">'+radar+'</div>'+
        '<div class="iq5-share-foot">'+S1.correct+'/'+S1.total+' correct · Streak '+S1.bestStreak+'</div>'+
      '</div>';

    const statsHtml =
      gauge +
      '<div class="iq5-res-title">🧠 Cognitive Report</div>'+
      '<div class="iq5-res-sub">Estimated IQ: <b style="color:'+cls.color+'">'+S1.iq+'</b> · '+cls.label+'</div>'+
      '<div class="iq5-res-sub">Better than approximately <b>'+pctile+'%</b> of players</div>'+
      '<div class="iq5-radar-host">'+radar+'</div>'+
      '<div class="iq5-skills">'+
        '<div class="iq5-skills-title">📊 Skill Breakdown</div>'+
        skillRows +
      '</div>'+
      '<div class="end-stats">'+
        '<div class="row"><span>Correct</span><span class="val">'+S1.correct+' / '+S1.total+'</span></div>'+
        '<div class="row"><span>Avg time / question</span><span class="val">'+(S1.avgMs/1000).toFixed(1)+'s</span></div>'+
        '<div class="row"><span>Best streak</span><span class="val">'+S1.bestStreak+' 🔥</span></div>'+
        '<div class="row"><span>Personal best</span><span class="val">'+Math.max(S1.iq, prevBest)+(newPB?' 🏆':'')+'</span></div>'+
      '</div>'+
      (strongest ? '<div class="iq5-verdict">💪 Strongest: <b>'+cap1(strongest[0])+'</b> ('+Math.round(strongest[1]*100)+'%) · 📈 Train more: <b>'+cap1(weakest[0])+'</b> ('+Math.round(weakest[1]*100)+'%)</div>' : '')+
      (tips.length ? '<div class="iq5-tips">'+tips.map(t=>'<div class="iq5-tip">'+t+'</div>').join('')+'</div>' : '')+
      shareCard +
      '<button class="iq5-share-btn" id="iqShareBtn">📤 Share Result</button>'+
      '<div class="iq5-disclaimer">⚠️ This estimated score is for brain-training entertainment. It is NOT a clinical IQ test and should not be used for academic or professional decisions.</div>';

    /* Call host end() — same shape as before */
    end({
      title: cls.label,
      emoji: '🧠',
      sub: 'Top '+(100-pctile)+'% · '+S1.correct+'/'+S1.total+' correct'+(newPB?' · 🏆 New Best!':''),
      value: S1.iq,
      points: S1.iq>=130 ? 14 : S1.iq>=110 ? 11 : S1.iq>=90 ? 8 : 5,
      starThresh: [90, 110, 130],
      statsHtml: statsHtml
    });

    /* Animate the gauge after the host has injected the HTML */
    _st(()=>{
      const arc = wrap.querySelector('#iqGaugeArc');
      const num = wrap.querySelector('#iqGaugeNum');
      if(arc){
        arc.style.transition = 'stroke-dashoffset 1.6s cubic-bezier(.22,1,.36,1)';
        arc.setAttribute('stroke-dashoffset', String(circ*(1-gPct)));
      }
      if(num){
        const t0 = performance.now();
        const step = t=>{
          const k = IQ_clamp((t-t0)/1400, 0, 1);
          const e = 1 - Math.pow(1-k, 3);
          num.textContent = Math.round(S1.iq*e);
          if(k<1) requestAnimationFrame(step);
        };
        requestAnimationFrame(step);
      }
      /* Share button */
      const shareBtn = wrap.querySelector('#iqShareBtn');
      if(shareBtn){
        shareBtn.addEventListener('click', ()=>{
          const text = 'I scored IQ '+S1.iq+' ('+cls.label+') on NeuroZen — top '+(100-pctile)+'% globally! 🧠 Can you beat it?';
          if(navigator.share){
            navigator.share({ title:'NeuroZen IQ', text }).catch(()=>{});
          }else if(navigator.clipboard){
            navigator.clipboard.writeText(text).then(()=>toast&&toast('📋 Copied!')).catch(()=>toast&&toast(text));
          }else{
            toast && toast(text);
          }
        });
      }
    }, 80);
  }

  /* -------- kick off -------- */
  if(!state.onboarded) showOnboarding();
  else startTest();
}

/* Expose to window in case any consumer expects it directly */
if(typeof window !== 'undefined'){
  window.playIQTest = playIQTest;
  window.IQ_POOL = IQ_POOL;
  window.IQ_CATS = IQ_CATS;
  window.IQ_TIMER = IQ_TIMER;
  window.IQ_N = IQ_N;
  window.iqClassify = iqClassify;
  window.IQ_QUESTIONS = IQ_QUESTIONS;
}
